### ISSUE TITLE
Expose rtm/start, or let user provide their own wss url

### ISSUE THREAD

**Issue by devth** [casidiablo/slack-rtm#2]
At https://github.com/casidiablo/slack-rtm/blob/master/src/slack_rtm/core.clj#L146-L147 lots of useful information returned by `rtm/start` is being discarded. This should be exposed to the end user, or else let them provide their own URL from calling `rtm/start` themselves so they can access the response data however they wish.

**Comment by devth** [comment]
This is addressed in my fork: https://github.com/devth/slack-rtm
I'm happy to submit a PR if interested.

**Comment by casidiablo** [comment]
Yes, please PR. 

Thanks.

**Comment by devth** [comment]
Sorry, I didn't see your reply as gh notifications were going to my spam folder. I'll PR soon.
